WordBased.space=\ 
WordBased.comma=
WordBased.commandand=
WordBased.commaspaceand=\ 
WordBased.commaspace=\ 
WordBased.spaceandspace=\ 
WordBased.year=y
WordBased.years=y
WordBased.month=m
WordBased.months=m
WordBased.week=w
WordBased.weeks=w
WordBased.day=d
WordBased.days=d
WordBased.hour=h
WordBased.hours=h
WordBased.minute=m
WordBased.minutes=m
WordBased.second=s
WordBased.seconds=s
WordBased.millisecond=ms
WordBased.milliseconds=ms
